spring.application.name=e-Motion-be

## SQL Server DB connection
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=e-Motion;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

## Hibernate JPA settings
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# JWT secret key
security.jwt.secret-key=70701be584b1f97a6a6e6104c7cf9bff7f7dc49e37b2b86afbbf20fcaa64a97c
security.jwt.expiration-time=3600000

# Mail properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=e.motion.vehicle1@gmail.com
spring.mail.password=aqdc itwb sfag owsj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

